import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className= "h-60 w-80 absolute block rounded-full bg-radial from-[#FF7ED4] via-[#FF3EA5]  to-[#6420AA] to 90% opacity-45 blur-3xl animate-move-along-x"></div>
        <div className= "h-60 w-80 absolute right-0 top-50 block rounded-full bg-radial from-[#FF7ED4] via-[#FF3EA5]  to-[#6420AA] to 90% opacity-45 blur-3xl animate-move-along-x"></div>
        <div className= "h-55 w-70 absolute bottom-0 left-120 block rounded-full bg-radial from-[#FF7ED4] via-[#FF3EA5]  to-[#6420AA] to 90% opacity-45 blur-3xl animate-move-along-x"></div>
        {children}
      </body>
    </html>
  );
}
